name: Run AWS CLI Command

on:
  push:
    branches:
      - main  # Specify which branch to run the action on, or modify as per your needs

jobs:
  run-aws-cli:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: eu-west-1  # Specify your region, update if needed

      - name: Run AWS CLI command
        run: |
          aws s3 ls  # Example command, change this to any AWS CLI command you wan
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: eu-west-1
      - name: Run AWS CLI Command
        run: |
          aws s3 mb s3://williamcaamotbucket
          aws s3 ls
          aws s3 rb s3://williamcaamotbucket
          aws s3 ls
          
